spring:
  datasource:
    url: jdbc:p6spy:h2:tcp://localhost/~/local-db/h2/conn/jpabasic
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    p6spy: info