spring:
  datasource:
    # Database 설정
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 DB를 모두 지우고 다시 생성한다.
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    # JPA 또는 hibernate 가 남기는 모든 SQL을 볼 수 있게 된다.
    org.hibernate.SQL: debug
    # org.hibernate.type: trace