spring:
  profiles:
    active: local

# job.name이 있으면 job.name값을 할당하고, 없으면 NONE을 할당
spring.batch.job.names: ${job.name:NONE}

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/testdb
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver