package me.study.testcodewitharchitecture.mock;

import me.study.testcodewitharchitecture.post.domain.Post;
import me.study.testcodewitharchitecture.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakePostRepository implements PostRepository {

    private Long autoGeneratedId = 0L;
    private final List<Post> data = new ArrayList<>();

    @Override
    public Optional<Post> findById(long id) {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                    .id(++autoGeneratedId)
                    .content(post.getContent())
                    .createdAt(post.getCreatedAt())
                    .modifiedAt(post.getModifiedAt())
                    .writer(post.getWriter())
                    .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(item -> item.getId().equals(post.getId()));
            data.add(post);
            return post;
        }
    }
}
